import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/Components/Cabecalho/Cabecalho";
import Rodape from "@/Components/Rodape/Rodape";
import Menu from "@/Components/Menu/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho />
        <Menu />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
