import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Cabecalho from "@/Components/Cabecalho/Cabecalho";
import Menu from "@/Components/Menu/Menu";
import Rodape from "@/Components/Rodape/Rodape";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
